name: Production FTP Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [production]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: production

      # Use Node.js and Install, Build
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: NPM install
        run: npm install

      - name: NPM build
        run: npm run build

      # List up output files
      # - name: list output files
      #   run: ls ./build

      # FTP deploy
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./build/
          server-dir: ./
          dry-run: true
